name: m3ak_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.8+29

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  percent_indicator: ^3.0.1
  flutter_rating_bar: ^4.0.0
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^7.0.0
  flutter_datetime_picker: ^1.5.1
  carousel_slider: ^4.1.1
  provider: ^6.0.1
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.13
  connectivity: ^3.0.6
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  auto_size_text: ^3.0.0
  qr_code_scanner: ^1.0.0
  firebase_messaging: ^11.4.0
  firebase_core: ^1.17.0
  flutter_local_notifications: ^9.5.3+1
  google_sign_in: ^5.3.2
  flutter_facebook_auth: ^4.3.4
  animation_wrappers: 0.0.2
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.19
  image_picker: ^0.8.4+4
  fancy_shimmer_image: ^2.0.0+2
  shimmer: ^2.0.0
  dio: ^4.0.4
  url_launcher: ^6.1.0
  pin_code_fields: ^7.4.0
  dotted_border: ^2.0.0+2
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.7.2+3
  geocoding: ^2.0.5
  permission_handler: ^10.2.0
  location: ^4.2.0
  screenshot: ^1.3.0
  image_gallery_saver: '^1.7.1'
  badges: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0


flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appIcon.png"





flutter:
  uses-material-design: true
  fonts:
     - family: ProductSans
       fonts:
         - asset: fonts/ProductSans-Regular.ttf
         - asset: fonts/ProductSans-Bold.ttf


  assets:
    - assets/
    - assets/male_avatar.png
    - assets/SellerImages/
    - assets/FooterIcons/
    - assets/PaymentIcons/
    - assets/CategoryImages/
    - assets/Medicines/


